apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-backend-ingress
  namespace: {{ .Values.appNamespace }}
  labels:
    app: test-backend-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.sslCertArn }}"
    external-dns.alpha.kubernetes.io/hostname: "app.{{ .Values.clusterName }}.{{ .Values.zoneName }}"
spec:
  rules:
  - host: "app.{{ .Values.clusterName }}.{{ .Values.zoneName }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-backend-service
            port:
              number: 8000