apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-backend-server
  namespace: argocd
spec:
  project: default
  source:
      repoURL: "https://github.com/cash4dog/final"
      targetRevision: HEAD
      path: workloads/test-backend-server
      helm:
        values: |
          sslCertArn: "{{ .Values.sslCertArn }}"
          clusterName: "{{ .Values.clusterName }}"
          zoneName: "{{ .Values.zoneName }}"
          imageTag: "{{ .Values.imageTag }}"
  destination:
      server: "https://kubernetes.default.svc"
      namespace: app-b-server
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true