apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-mgr
  namespace: argocd
spec:
  project: default
  source:
      repoURL: "https://github.com/cash4dog/final"
      targetRevision: HEAD
      path: apps
      helm:
        parameters:
          - name: clusterName
            value: "{{ .Values.clusterName }}"
          - name: zoneName
            value: "{{ .Values.zoneName }}"
          - name: appNamespace
            value: "{{ .Values.appNamespace }}"
          - name: sslCertArn
            value: "{{ .Values.sslCertArn }}"
          - name: gitCommitSha
            value: "$ARGOCD_APP_REVISION"
  destination:
      server: "https://kubernetes.default.svc"
      namespace: "{{ .Values.appNamespace }}"
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
